version: "3.9"

services:
  postgresdb:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=myapplication
    ports:
      - '5432:5432'
    volumes: 
      - postgresdb:/var/lib/postgresql/data
volumes:
  postgresdb:
    driver: local